//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurseryAssigner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalDay
    {
        public long ID { get; set; }
        public System.DateTime Date { get; set; }
        public string AMPM { get; set; }
        public string Description { get; set; }
    }
}
