//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurseryAssigner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attendant()
        {
            this.AttendantSchedules = new HashSet<AttendantSchedule>();
        }
    
        public long ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public long AgeGroupID { get; set; }
        public bool DoesAM { get; set; }
        public bool DoesPM { get; set; }
        public Nullable<long> GradYear { get; set; }
        public Nullable<System.DateTime> ExclusionStart { get; set; }
        public Nullable<System.DateTime> ExclusionEnd { get; set; }
        public bool IsInactive { get; set; }
        public string Comment { get; set; }
    
        public virtual AgeGroup AgeGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendantSchedule> AttendantSchedules { get; set; }
    }
}
