//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurseryAssigner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendantSchedule
    {
        public long ID { get; set; }
        public long ScheduledDayID { get; set; }
        public long AttendantID { get; set; }
        public long Position { get; set; }
    
        public virtual Attendant Attendant { get; set; }
        public virtual ScheduledDay ScheduledDay { get; set; }
    }
}
