//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurseryAssigner.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NurseryAssignerEntities : DbContext
    {
        public NurseryAssignerEntities()
            : base("name=NurseryAssignerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgeGroup> AgeGroups { get; set; }
        public virtual DbSet<Attendant> Attendants { get; set; }
        public virtual DbSet<AdditionalService> AdditionalServices { get; set; }
        public virtual DbSet<AssignmentCount> AssignmentCounts { get; set; }
        public virtual DbSet<AttendantSchedule> AttendantSchedules { get; set; }
        public virtual DbSet<Service> Services { get; set; }
    }
}
