//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurseryAssigner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledDay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduledDay()
        {
            this.AttendantSchedules = new HashSet<AttendantSchedule>();
        }
    
        public long ID { get; set; }
        public System.DateTime Date { get; set; }
        public string AMPM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendantSchedule> AttendantSchedules { get; set; }
    }
}
